apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: template-net-core-api-hpa
  namespace: template-net-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: template-net-core-api-dep
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90